export const DEFAULT_CATEGORIES = [
	"Electronics",
	"Electronics > Mobile Phones",
	"Electronics > Mobile Phones > Tablets",
	"Electronics > Mobile Phones > E-Readers",
	"Electronics > Mobile Phones > Wearables & Smart Watches",
	"Electronics > Mobile Phones > Mobile & Gadget Accessories",
	"Electronics > Mobile Phones > Walkie-Talkies",
	"Electronics > Mobile Phones > Other Gadgets",
	"Electronics > Computers & Tech",
	"Electronics > Computers & Tech > Laptops & Notebooks",
	"Electronics > Computers & Tech > Desktops",
	"Electronics > Computers & Tech > Parts & Accessories",
	"Electronics > Computers & Tech > Printers",
	"Electronics > Computers & Tech > Scanners & Copiers",
	"Electronics > Computers & Tech > Office & Business Technology",
	"Electronics > Computers & Tech > Rentals",
	"Electronics > Video Gaming",
	"Electronics > Video Gaming > Video Game Consoles",
	"Electronics > Video Gaming > Video Games",
	"Electronics > Video Gaming > Gaming Accessories",
	"Electronics > Video Gaming > Rentals",
	"Electronics > TV & Home Appliances",
	"Electronics > TV & Home Appliances > TV & Entertainment Systems",
	"Electronics > TV & Home Appliances > Kitchen Appliances",
	"Electronics > TV & Home Appliances > Household Appliances",
	"Electronics > TV & Home Appliances > Rentals",
	"Electronics > Audio-Visual (AV) Equipment",
	"Electronics > Audio-Visual (AV) Equipment > Cameras",
	"Electronics > Audio-Visual (AV) Equipment > Lens & Kits",
	"Electronics > Audio-Visual (AV) Equipment > Drones",
	"Electronics > Audio-Visual (AV) Equipment > Video Cameras",
	"Electronics > Audio-Visual (AV) Equipment > Photography Accessories",
	"Electronics > Audio-Visual (AV) Equipment > Earphones",
	"Electronics > Audio-Visual (AV) Equipment > Headphones & Headsets",
	"Electronics > Audio-Visual (AV) Equipment > Microphones",
	"Electronics > Audio-Visual (AV) Equipment > Soundbars",
	"Electronics > Audio-Visual (AV) Equipment > Speakers & Amplifiers",
	"Electronics > Audio-Visual (AV) Equipment > Portable Music Players",
	"Electronics > Audio-Visual (AV) Equipment > Rentals",
	"Fashion & Beauty",
	"Fashion & Beauty > Women's Fashion",
	"Fashion & Beauty > Women's Fashion > Activewear",
	"Fashion & Beauty > Women's Fashion > Maternity Wear",
	"Fashion & Beauty > Women's Fashion > Tops",
	"Fashion & Beauty > Women's Fashion > Bottoms",
	"Fashion & Beauty > Women's Fashion > Dresses & Sets",
	"Fashion & Beauty > Women's Fashion > Footwear",
	"Fashion & Beauty > Women's Fashion > Swimwear",
	"Fashion & Beauty > Women's Fashion > Coats & Outerwear",
	"Fashion & Beauty > Women's Fashion > Bags & Wallets",
	"Fashion & Beauty > Women's Fashion > Jewelry & Organizers",
	"Fashion & Beauty > Women's Fashion > Watches & Accessories",
	"Fashion & Beauty > Women's Fashion > Undergarments & Loungewear",
	"Fashion & Beauty > Men's Fashion",
	"Fashion & Beauty > Men's Fashion > Activewear",
	"Fashion & Beauty > Men's Fashion > Tops & Sets",
	"Fashion & Beauty > Men's Fashion > Bottoms",
	"Fashion & Beauty > Men's Fashion > Footwear",
	"Fashion & Beauty > Men's Fashion > Coats & Outerwear",
	"Fashion & Beauty > Men's Fashion > Bags",
	"Fashion & Beauty > Men's Fashion > Watches & Accessories",
	"Fashion & Beauty > Luxury",
	"Fashion & Beauty > Luxury > Luxury Bags & Wallets",
	"Fashion & Beauty > Luxury > Luxury Apparel",
	"Fashion & Beauty > Luxury > Luxury Accessories",
	"Fashion & Beauty > Luxury > Luxury Watches",
	"Fashion & Beauty > Luxury > Luxury Sneakers & Footwear",
	"Fashion & Beauty > Beauty & Personal Care",
	"Fashion & Beauty > Beauty & Personal Care > Fragrance & Deodorants",
	"Fashion & Beauty > Beauty & Personal Care > Bath & Body",
	"Fashion & Beauty > Beauty & Personal Care > Face",
	"Fashion & Beauty > Beauty & Personal Care > Hair Products",
	"Fashion & Beauty > Beauty & Personal Care > Men's Grooming",
	"Fashion & Beauty > Beauty & Personal Care > Hands & Nails",
	"Fashion & Beauty > Beauty & Personal Care > Vision Care",
	"Fashion & Beauty > Beauty & Personal Care > Oral Care",
	"Miscellaneous / Other (Extracted from middle/back)",
	"Miscellaneous / Other (Extracted from middle/back) > Bathroom & Kitchen Accessories",
	"Miscellaneous / Other (Extracted from middle/back) > Travel",
	"Miscellaneous / Other (Extracted from middle/back) > Flowers & Bouquets",
	"Miscellaneous / Other (Extracted from middle/back) > Religious Items",
	"Sports",
	"Sports > Bicycles",
	"Sports > Fitness Equipment",
	"Sports > Team Sports",
	"Sports > Racket Sports",
	"Sports > Camping & Hiking",
	"Sports > Turfs/Courts/Stadiums/Grounds/Tracks",
	"Pet Supplies",
	"Pet Supplies > Pets",
	"Pet Supplies > Pet food & Accessories",
	"Pet Supplies > Fish & Aquarium",
	"Food & Drinks",
	"Food & Drinks > Restaurants",
	"Food & Drinks > Local Eats",
	"Food & Drinks > Packaged Food",
	"Food & Drinks > Beverages",
	"Food & Drinks > Fresh Produce",
	"Food & Drinks > Homemade Bakes",
	"Health & Wellness",
	"Health & Wellness > Gym & Fitness",
	"Health & Wellness > Nutrition Products",
	"Health & Wellness > Natural Products",
	"Vehicles",
	"Vehicles > Cars",
	"Vehicles > Cars > Used Cars",
	"Vehicles > Cars > New Cars",
	"Vehicles > Cars > Parallel Imports",
	"Vehicles > Cars > Car Rental",
	"Vehicles > Cars > Other Vehicles",
	"Vehicles > Car Accessories",
	"Vehicles > Car Accessories > Parts",
	"Vehicles > Car Accessories > Accessories",
	"Vehicles > Car Accessories > Car Care",
	"Vehicles > Motorcycles",
	"Vehicles > Motorcycles > Motorcycles for Sale",
	"Vehicles > Motorcycles > Accessories",
	"Vehicles > Motorcycles > Apparel",
	"Vehicles > Motorcycles > Rental",
	"Vehicles > Commercial Vehicles & Spares",
	"Vehicles > Commercial Vehicles & Spares > Trucks",
	"Vehicles > Commercial Vehicles & Spares > Pick-up Vans",
	"Vehicles > Commercial Vehicles & Spares > Tractors",
	"Vehicles > Commercial Vehicles & Spares > Taxi Cabs",
	"Vehicles > Commercial Vehicles & Spares > Auto-rickshaws",
	"Vehicles > Commercial Vehicles & Spares > Buses",
	"Vehicles > Commercial Vehicles & Spares > Heavy Machinery",
	"Vehicles > Commercial Vehicles & Spares > Wheels & Tyres",
	"Vehicles > Commercial Vehicles & Spares > Audio & Other Accessories",
	"Vehicles > Commercial Vehicles & Spares > Battery",
	"Property",
	"Property > For Sale: Houses & Apartments",
	"Property > For Rent: Houses & Apartments",
	"Property > For Sale: Shops, Offices & Warehouses",
	"Property > For Rent: Shops, Offices & Warehouses",
	"Property > Marriage & Community Halls",
	"Property > PG & Guest Houses",
	"Property > For Sale: Lands & Plots",
	"Property > For Rent: Lands & Plots",
	"Property > Resorts & Clubs",
	"Property > Hotels",
	"Property > Bars",
	"Funeral Services",
	"Hospitals & Clinics",
	"Services",
	"Services > Education & Classes",
	"Services > Electronics Repair",
	"Services > Home Renovation, Repair & Cleaning",
	"Services > Vehicle Service",
	"Services > Salon, Spa & Sauna",
	"Services > Taxi & Tourist Services",
	"Services > Call Driver",
	"Services > Guides",
	"Services > Packers & Movers",
	"Services > Maids & Nurses",
	"Services > Courier Services",
];
